;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Cum Mar 11 2016
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
STAK    SEGMENT PARA STACK 'STACK'
        DW 20 DUP(?)
STAK    ENDS

DATA    SEGMENT PARA 'DATA'
; 8254 REGISTER ADDRESSES
CW EQU 87H
CNTR0 EQU 89H
CNTR1 EQU 8BH
CNTR2 EQU 8DH
DATA    ENDS

CODE    SEGMENT PARA 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STAK
START PROC FAR
        MOV AX, DATA
        MOV DS, AX
        
        MOV AL, 00110100B ; CNTR0, LSb then MSb,  mod2, binary
        OUT CW, AL
        
        MOV AL, 01010100B ; CNTR1, LSb,  mod2, binary
        OUT CW, AL
        
        MOV AX, 1000
        OUT CNTR0, AL
        MOV AL, AH
        OUT CNTR0, AL
        
        MOV AL, 100
        OUT CNTR1, AL
        
ENDLESS:
        JMP ENDLESS
RETF
START ENDP

CODE    ENDS
        END START
